version: '3.4'

services:
    azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      ports:
        - "10000:10000"
        - "10001:10001"
      volumes:
          - c:/azurite:/workspace mcr.microsoft.com/azure-storage/azurite azurite
    woffu-function:
        restart: always
        image: localhost:5000/woffu-function
        environment:
          - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
          - "80"
        depends_on:
            - azurite